
AIM

To write a Java program to demonstrate Thread Priority by creating three threads and assigning different priority levels using setPriority().

ALGORITHM
Start the program.
Create three classes A, B, and C by extending the Thread class.
Override the run() method in each class.
Create objects threadA, threadB, and threadC.
Set the priority of:
Thread A → MIN_PRIORITY = 1
Thread B → NORM_PRIORITY = 5
Thread C → MAX_PRIORITY = 10
Start all three threads using the start() method.
Each thread executes its run() method.
Display the messages and numbers generated by each thread.
Stop the program
    class A extends Thread {
    public void run() {
        System.out.println("Thread A started");
        for (int i = 1; i <= 4; i++) {
            System.out.println("from thread A i=" + i);
        }
        System.out.println("exit from A");
    }
}

class B extends Thread {
    public void run() {
        System.out.println("Thread B started");
        for (int j = 1; j <= 4; j++) {
            System.out.println("from thread B j=" + j);
        }
        System.out.println("exit from B");
    }
}

class C extends Thread {
    public void run() {
        System.out.println("thread c started");
        for (int k = 1; k <= 4; k++) {
            System.out.println("thread c=" + k);
        }
        System.out.println("exit from c");
    }
}

class ThreadPriority {
    public static void main(String[] args) {
        A threadA = new A();
        B threadB = new B();
        C threadC = new C();

        // Setting priorities
        threadA.setPriority(Thread.MIN_PRIORITY); // Priority 1
        threadB.setPriority(Thread.NORM_PRIORITY); // Priority 5
        threadC.setPriority(Thread.MAX_PRIORITY); // Priority 10

        // Starting threads
        threadA.start();
        threadB.start();
        threadC.start();
    }
}
OUTPUT
One possible output is:
Thread A started
from thread A i=1
from thread A i=2
from thread A i=3
from thread A i=4
exit from A
Thread B started
from thread B j=1
from thread B j=2
from thread B j=3
from thread B j=4
exit from B
thread c started
thread c=1
thread c=2
thread c=3
thread c=4
exit from c
RESULT
Thus, the Java program to demonstrate thread priority using MIN_PRIORITY, NORM_PRIORITY, and MAX_PRIORITY was executed successfully and the desired output was obtained.
